#Common Properties

deployment:
  url: "https://anypoint.mulesoft.com"
  muleVersion: "4.4.0"
  region: "us-east-1"
  osv2: "true"
  
http:
  host: "0.0.0.0"
  port: "8081"
https:
  host: "0.0.0.0"
  port: "8082"
  private:
    port: "8092"