#Environment Specific Properties:  ~~~ DEV Properties ~~~

api:
  id: "xxss"
  
deployment:
  workers: "1"
  workerType: "MICRO"
  http:
    listner:
      port: "8081"
      
app:
  sfSapi:
    host: "dd-fdsaffadsfas-u8jh37.5sc6y6-3.usa-e2.cloudhub.io"
    port: "443"
  

