{
  "successful": false,
  "response": [
    {
      "contactId": "003Dz00002NNiR2IAL",
      "success": true
    },
    {
      "contactId": "003Dz00002NNiR3TAL",
      "success": false,
      "error": "Contact ID: id value of incorrect type: 003Dz00002NNiR3TAL MALFORMED_ID"
    }
  ]
}