{
    "accountRecordId": "001Dz00002jJCshIAG",
    "contactRecordId": "001Dz00002jJCshIAG",
    "aNumber": "A02345523",
    "firstName": "Lebron",
    "lastName": "James",
    "middleName": "Jemy",
    "sex": "Male",
    "birthDate": "2025-04-25",
    "emailAddress": "guy.ballard@usu.edu",
    "bannerAddressType": "home",
    "street": "1464 Lynnwood Ave",
    "city": "Logan",
    "stateCode": "Utah",
    "postalCode": "84341",
    "country": "United States",
    "phoneType": "mobile",
    "phoneNumber": "4352321637"
}