[
  {
    "indvAppId": "001Dz00002jJCshIAG",
    "bannerStatus": "reviewRequired",
    "bannerGuid" : "04a03680-a22f-4fe6-b036-ce2c923b8078"
  },
  {
    "indvAppId": "001Dz00002jJCshIAG",
    "bannerStatus": "reviewRequired",
    "bannerGuid" : "04a03680-a22f-4fe6-b036-ce2c923b8078"
  }
]