{
  "successful": false,
  "response": [
    {
      "indvAppId": "001Dz00002jJCshIAG",
      "success": true
    },
    {
      "indvAppId": "001Dz00002jJCshIAG",
      "success": false,
      "error": "Application Id: id value of incorrect type: 001Dz00002jJCshIAG MALFORMED_ID"
    }
  ]
}