#%RAML 1.0 DataType
  properties:
    errorCode: 
      type: string
      required: false
    errorMessage:
      type: string
      required: false 
    transactionId: 
      type: string
      required: false
    timeStamp: 
      type: datetime
      required: false
